[tool.poetry]
authors = []
description = ""
name = "protostar_cairo_py"
packages = [{include = "protostar_cairo_py"}]
readme = "README.md"
version = "0.1.0"

[tool.poe.tasks.build]
shell = "cd protostar-cairo/crates/cairo-lang-python-bindings && rustup override set nightly && maturin build --release --strip --out ../../../cairo_python_bindings"

[tool.poetry.dependencies]
python = ">=3.9.14, <3.10"

[tool.poetry.group.dev.dependencies]
maturin = "^0.14.13"
poethepoet = "^0.18.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
